name: admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9
  image_picker_for_web: ^3.0.4
  image_picker: ^1.1.2
  gap: ^3.0.0
  get: ^4.6.5
  provider: ^6.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
